version: '3.8'

services:
  flyway:
    image: flyway/flyway
    container_name: flyway-book
    
    volumes:
      - ./db-migrations/book-service:/flyway/sql  # Path to your migrations
    command: -url=jdbc:mysql://mysqldb:3306/Book -user=root -password=root migrate
    networks:
      - app-network  # Reuse the existing network

networks:
  app-network:
    external: true  # Make sure this matches the network in your main docker-compose.yml
