version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Book
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: affan341/springboot-mysql-docker
    container_name: springboot-app
    depends_on:
      mysql:
        condition: service_healthy  # ✅ this waits for MySQL to be healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/Book?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8765:8765"
    networks:
      - app-network
  
  flyway:
    image: flyway/flyway
    container_name: flyway-book
    depends_on:
      mysql:
        condition: service_healthy
    
    volumes:
      - ./db-migrations/book-service:/flyway/sql  # Path to your migrations
    command: -url=jdbc:mysql://mysqldb:3306/Book -user=root -password=root migrate
    networks:
      - app-network
networks:
  app-network:
